groups/urls.py
from django.urls import path

from groups import views

app_name = 'groups'

urlpatterns = [
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug:slug>',views.SingleGroup.as_view(),name='single'),
    path('join/<slug:slug>',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug:slug>',views.LeaveGroup.as_view(),name='leave')
]

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<str:username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<str:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>',views.PostDelete.as_view(),name='delete'),

]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),

    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),
    
    #using default urls from django for login and logout
    path('accounts/',include('django.contrib.auth.urls')),

    path('test/',views.TestView.as_view(),name='test'),
    path('thanks/',views.ThanksView.as_view(),name='thanks'),

]

groups/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from django.contrib.auth import get_user_model
import misaka

#getting user from get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()

# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=254,unique = True)
    slug = models.SlugField(allow_unicode = True, unique = True)
    description = models.TextField()
    description_html = models.TextField(editable = False,default = '', blank = True)
    members = models.ManyToManyField(User,through = 'GroupMember')

    def __str__(self):
        return self.name


    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name = 'memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name = 'user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('user','group')

groups/views.py
from django.shortcuts import render
from django.contrib import messages

from groups.models import Group,GroupMember
from django.views import generic

from django.urls import reverse
from django.shortcuts import get_object_or_404

from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin


# Create your views here.
class CreateGroup(LoginRequiredMixin,generic.CreateView):
    model = Group
    fields = ('name','description')

class SingleGroup(generic.DetailView):
    model = Group
    context_object_name = 'group_detail'

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):

        return reverse('groups:single', kwargs = {'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        #get object of the group
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            #create a group and member, as we have to insert group id and user id
            GroupMember.objects.create(user=self.request.user,group=group)
        except:
            messages.warning(self.request,'User is already a member')
        else:
            messages.success(self.request,'User is now a member')

        return super().get(request,*args,**kwargs)


class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single", kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )

        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)
"""
    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self,request,*args,**kwargs):

        try:
            #we always check via slug instead of id
            membership = GroupMember.objects.filter(user=self.request.user,group__slug=self.kwargs.get("slug")).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request,'User is not member of this group')
        else:
            membership.delete()
            message.success(self.request,'membership deleted')

        return super().get(request,*args,**kwargs)"""

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}

  <div class="container">
    <div class="row">
      {% block pregroup %}       {% endblock %}
      {% block group_content %}  {% endblock %}
      {% block post_group %}     {% endblock %}
    </div>
  </div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}

  <h1>{{group_detail.name}}</h1>
  <h2>Member Count: {{group_detail.members.count}}</h2>

  <div class="content">

    {% if user in group_detail.members.all %}
      <a href="{% url 'groups:leave' slug=group_detail.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span>>Leave</a>
    {% else %}
      <a href="{% url 'groups:join' slug=group_detail.slug %}" class="btn btn-lg btn-fill btn-success"><span class="glyphicon glyphicon-ok-circle"></span>>Join</a>
    {% endif %}

  </div>

{% endblock %}

{% block group_content %}
  <div class="col-m-8">

    {% if group.posts.count == 0 %}
      <h2>No Posts inthis group yet! </h2>
    {% else %}
      {% for post in group.posts.all %}
        {% include 'posts/_post.html' %}
      {% endfor %}
    {% endif %}

  </div>

{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap3 %}

{% block group_content %}
  <h3>Create a new Form: </h3>

  <form action="{% url 'groups:create' %}" method="post">

    {% csrf_token %}
    {% bootstrap_form form %}

    <input type="Submit" class="btn btn-primary" value="Create">
  </form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
  <div class="col-md-4">
    <div class="content">

      {% if user.is_authenticated %}
        <h2>Welcome Back
          <a href="{% url 'posts:for_user' username=user.username%}">
            @{{user.username}}
          </a>
        </h2>
      {% endif %}

      <h2>Groups</h2>
      <p>Welcome to the groups page!</p>

    </div>

    {% if user.is_authenticated %}
      <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
        <span class="glypicon glypicon-plus-sign">Create New Group</span>
      </a>
    {% endif %}

  </div>

{% endblock %}

{% block group_content %}

  <div class="col-md-8">
    <div class="list-group">

      {% for group in group_list %}

        <a href="{% url 'groups:single' slug=group.slug %}">
          <h3>{{ group.name }}</h3>

          <div class="container-fluid">
            {{ group.description_html|safe }}

            <div class="col-md-4">
              <span class='badge'>{{group.memberships.count }}</span>
              member{{ group.members.count|pluralize }}
            </div>

            <div class="col-md-4">
              <span class="badge">{{ group.posts.count }}</span>
              post{{ group.posts.count|pluralize }}
            
            </div>

          </div>
        </a>

      {% endfor %}

    </div>
  </div>

{% endblock %}