accounts/urls.py
from django.contrib.auth import views as auth_views
from accounts import views
from django.urls import path

#for template tagging
app_name = 'accounts'

#login and logout has automatic views
urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUP.as_view(),name='signup'),
]

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<str:username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<str:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>',views.PostDelete.as_view(),name='delete'),

]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),

    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),
    
    #using default urls from django for login and logout
    path('accounts/',include('django.contrib.auth.urls')),

    path('test/',views.TestView.as_view(),name='test'),
    path('thanks/',views.ThanksView.as_view(),name='thanks'),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>SimpleSocial</title>

    <!-- boostrap css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
    <!-- master css -->
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">
    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

  </head>
  <body>
    <nav class="navbar" role="navigation" id="navbar">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Star Social</a>
        <ul class="nav navbar-nav navbar-right">

          {% if user.is_authenticated %}
            <li><a href="{% url 'posts:create' %}"> Post </a></li>
            <li><a href="{% url 'groups:all' %}"> Groups </a></li>
            <li><a href="{% url 'groups:create' %}"> Create Group </a></li>
            <li><a href="{% url 'accounts:logout' %}"> Log-Out </a></li>
          {% else %}
            <li><a href="{% url 'groups:all' %}"> Groups </a></li>
            <li><a href="{% url 'accounts:login' %}"> Log In </a></li>
            <li><a href="{% url 'accounts:signup' %}"> Sign Up </a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
      {% block content %}

      {% endblock %}

  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>Welcome to Star Social</h1>
</div>
{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h1>You are now logged In</h1>
  </div>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">

    <h1>Thanks for visitng the page</h1>
  </div>
{% endblock %}