posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<str:username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<str:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>',views.PostDelete.as_view(),name='delete'),

]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),

    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),
    
    #using default urls from django for login and logout
    path('accounts/',include('django.contrib.auth.urls')),

    path('test/',views.TestView.as_view(),name='test'),
    path('thanks/',views.ThanksView.as_view(),name='thanks'),

]

posts/models.py
from django.db import models
from groups.models import Group, GroupMember

from django.utils.text import slugify
from django.urls import reverse

from django.contrib.auth import get_user_model
import misaka

#getting user
User = get_user_model()

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User,related_name = 'posts',on_delete=models.CASCADE)
    group = models.ForeignKey(Group,related_name = 'posts', on_delete=models.CASCADE, null = True, blank = True)
    message = models.TextField()
    message_html = models.TextField(editable = False)
    created_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.user

    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs = {'pk':self.pk,'username':self.user.username})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

posts/views.py
from django.shortcuts import render
from django.contrib import messages

from posts import models
from groups.models import Group,GroupMember

from posts import forms
from django.views import generic

from django.contrib import messages

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin
from django.contrib.auth import get_user_model

User = get_user_model()

class PostList(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ('user','group')

    #We will be dividing with logged_in user group and other_user group
    #is user logged in show user group or show other group
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)

        self.get_user_group = Group.objects.filter(members__in=[self.request.user])
        context['get_user_group'] = self.get_user_group

        self.get_other_group = Group.objects.exclude(members__in=[self.request.user]) #id
        context['get_other_group'] = self.get_other_group

        return context

class UserPosts(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ('user','group')
    template_name = 'user_post_list.html'

    #how many post does that user have
    def get_queryset(self):

        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact = self.kwargs.get('username'))

        except User.DoesNotExist:
            raise Http404

        else:
            #user.posts.all() shows all the user post_user
            #but we need only posts of logged in user so
            #above query in try
            return self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context


class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact = self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    model = models.Post
    fields = ('message','group')

    def form_valid(self,form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)

class PostDelete(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ('user','group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

posts/templates/posts/_post.html
<!-- display individual post detail -->

<div class="post media">
  <h3>{{post.message_html|safe}}</h3>

  <div class="media-body">
    <strong>{{post.user.username}}</strong>
    <h5 class="nedia-heading">
      <span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
			<time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>

      {% if post.group %}
        <span class="group-name">in <a href="#">{{ post.group.name }}</a></span>
      {% endif %}
    </h5>

    <div class="media-footer">
      {% if user.is_authenticated and post.user == user %}
      <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-primary">
        <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>

        <span class="text-danger icon-label">Delete</span>
      </a>
      {% endif %}
    </div>
  </div>
</div>

posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block content %}

<div class="posts-page">
  <div class="container">
    <div class="row">

      {% block pre_post %}      {% endblock %}
      {% block post_content %}  {% endblock %}
      {% block post_post %}     {% endblock %}

    </div>
  </div>
</div>

{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block pre_post %}

<h3>Are you sure want to delete?</h3>

<div class="posts">
  {% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn=danger" value="Delete">
   <a class="btn btn-primary" href="{% url 'posts:single' username=user.username pk=object.pk %}">Cancel</a>
</form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}

{% block post_content %}

<div class="col-md-8">
  {% include 'posts/_post.html' %}
</div>

{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap3 %}

{% block post_content %}

  <h1>Create a new post</h1>

  <form action="{% url 'posts:create' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

    <input type="submit" class="btn btn-primary" value="Create">
  </form>

{% endblock %}

posts/templates/posts/post_list.html
<!-- display individual post list and list of groups -->

{% extends 'posts/post_base.html' %}
{% block pre_post %}

<div class="col-md-4">
  {% if request.user_is.authenticated %}

  <div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
        {% for user_group in get_user_group %}

        <li class="group li-with-bullet">
          <a href="{% url 'groups:single' slug=member_group.group.slug %}">{{user_group.group.name}}</a>
        </li>

        {% endfor%}
      </ul>
    </div>
  </div>

  {% endif%}

  <div class="card card-with-shadow">
    <div class="content">
      <h5 class="title">All groups</h5>
      <ul class="list-unstyled">

        {% for other_group in get_other_group %}
          <li class="group li-with-bullet">
            <a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

{% endblock %}


{% block post_content %}
<div class="col-md-8">
  {% for post in post_list %}
    {% include 'posts/_post.html' %}
  {% endfor %}
</div>
{% endblock %}

posts/templates/posts/user_post_list.html
<!-- display list of post of logged in user -->

{% extends 'posts/post_base.html' %}

{% block pre_post %}

  <div class="col-md-4">
    <h3>@{{post_user.username}}</h3>
    <p>Post History</p>
  </div>

{% endblock %}

{% block post_content %}

<div class="col-md-8">
  {% for post in post_user %}
    {% include('posts/_post.html') %}
  {% endfor %}
</div>

{% endblock %}